name: CI

on:
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Create build dir
        run: mkdir build
      - name: Compile Manual
        uses: dante-ev/latex-action@latest
        with:
          working_directory: build
          root_file: ../jediacademy_plugins_doc.tex
      - name: Package plugin
        uses: TheDoctor0/zip-release@0.6.0
        with:
          directory: build
          path: ..
          filename: jediacademy.zip
          exclusions: '.git/* .github/* build/* *.tex *.pdf *.zip notes.txt README.md todo.txt'
          type: zip
      - name: Release nightly
        uses: softprops/action-gh-release@v1
        with:
          name: nightly
          tag_name: nightly
          prerelease: true
          body: |
            Automatic pre-release build.
            
            The jediacademy.zip file can be installed using the button in Blender's add-on preferences.
            
            Please consult jediacademy_plugins_doc.pdf for instructions on how to use the plugin.
            
            Latest change:
            
            ${{github.event.commits[0].message}}
          files: |
            build/jediacademy_plugins_doc.pdf
            build/jediacademy.zip
