name: CI

on:
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile Manual
        uses: dante-ev/latex-action@latest
        with:
          root_file: jediacademy_plugins_doc.tex
      - name: Package plugin
        uses: TheDoctor0/zip-release@0.6.0
        with:
          filename: jediacademy.zip
          path: ./jediacademy/
          type: zip
      - name: Release nightly
        uses: softprops/action-gh-release@v1
        with:
          name: nightly
          files: |
            jediacademy_plugins_doc.pdf
            jediacademy.zip
